- other/js/package.json
Added websockify.js to the files section, this fixes #90 and allows NPM to properly install
> Fixed Package.json

- websockify/__init__.py
- websockify/websocketproxy.py
Implicit relative imports don't work in Python 3.  This converts
implicit relative imports into absolute imports
(e.g. `import websocket` becomes `from websockify import websocket`).
Fixes #154
> Don't use implicit relative imports

- setup.py
This makes <http://py3readiness.org> display the status of this package correctly :).
> Add Python 3 trove classifiers.

- websockify/websocket.py
This patch fixes noVNC endianess problem on handshake.
It affects noVNC sessions on Big Endian platforms.
Fixes #150
> BUGFIX:  Websocket frame corruption on big-endian #150

- websockify/websocket.py
- websockify/websocketproxy.py
Implementations to handle ping and pong heartbeat messages to help with connections through firewalls or proxies and such where regular keep alive traffic would be required.
> Implement Ping and Pong heartbeat messages

- .gitignore
- .travis.yml
- test-requirements.txt
- tests/test_websocket.py
- tests/test_websocketproxy.py
- tox.ini
- websockify/auth_plugins.py
- websockify/token_plugins.py
- websockify/websocket.py
- websockify/websocketproxy.py
This PR introduces auth hooks, with allow websockify users to easily add in arbitrary authentication without having to subclass the main classes of websockify.  Authentication plugins are passed the header object, as well as the target host and port.  When initialized, they are passed a single parameter, similarly to token plugins.  If authentication fails, auth plugins should raise an exception.
> Auth Plugins / Plugin Cleanup

- tests/test_websocket.py
- websockify/websocket.py
This commit introduces strict mode, which is on by default.  Currently
strict mode only enforces client-to-server frame masking.  However,
in the future, it might enforce other parts of the RFC as well.
Closes #164
> Introduce strict mode

- websockify/websocketproxy.py
Closes #166 
Obsoletes PR #167
> Catch interrupted system call

- run
Similar to websocify.py, just a convenience fix.
> Make `run` respect virtualenv configuration

- other/js/package.json
Fixes the following warning on `npm install`:
```
npm WARN package.json websockify@0.7.0 license should be a valid SPDX license expression
```
The identifier LGPL-3.0 was retrieved from https://spdx.org/licenses/.
> Correct SPDX license identifier for LGPL-3.0

- .gitignore
36cb8f4676c7b5ff34bd22ad729e00e77efb6f00 moved the JavaScript source, but the entry ignoring `node_modules` was not updated in unison.
> Ignore node_modules correctly

- other/js/package.json
Since 805026360e591ef6b27eb069e90ffccb31f72d1f this dependency has not been in use.
It also prevents using Websockify on Node v0.12.0:
```
npm WARN package.json websockify@0.7.0 license should be a valid SPDX license expression
-
> base64@2.1.0 install /Users/timkurvers/Projects/forks/websockify/other/js/node_modules/base64
> node-gyp rebuild
CXX(target) Release/obj.target/base64/base64.o
../base64.cc:13:17: error: calling a protected constructor of class 'v8::HandleScope'
HandleScope scope;
^
/Users/timkurvers/.node-gyp/0.12.6/deps/v8/include/v8.h:816:13: note: declared protected here
V8_INLINE HandleScope() {}
^
../base64.cc:14:52: error: no member named 'New' in 'v8::String'
return ThrowException(Exception::Error(String::New(msg)));
~~~~~~~~^
../base64.cc:122:29: error: unknown type …
```
> Drop pkrumins/node-base64 dependency

- tests/test_websocketproxy.py
- websockify/auth_plugins.py
- websockify/websocket.py
- websockify/websocketproxy.py
This commit reworks auth plugins slightly to enable
support for HTTP authentication.  By raising an
AuthenticationError, auth plugins can now return
HTTP responses to the upgrade request (such as 401).
Related to kanaka/noVNC#522
> Rework Auth Plugins to Support HTTP Auth

- tests/test_auth_plugins.py
- websockify/auth_plugins.py
```python
pull_request_description = "no comment"
```
> Verify username/password with BasicAuth plugin

- websockify/websocket.py
- websockify/websocketproxy.py
Override log_message in websocket.py so messages from send_error are properly saved into the log files
Closes #204
> Add support for log files

- websockify/websocket.py
Openstack nova novnc-proxy services uses websockify to provide support
for nova vms using novnc proxy. At present, novnc hangs every couple of
weeks. It only resumes post restart of the novnc-proxy which is not
good. Hence, this code in websockify is updated to get rid of additional
signal calls to avoid novnc going in hang state even though process is
running. Basically, we are getting rid of existing msg and vmsg calls in
the websocket.py. This is kind of quick fix but we will need an
additional way of figuring out the logging to make it easy to trace in
case of any further failures in future.
closes bug: https://github.com/kanaka/noVNC/issues/556
> Remove additional signal calls in websockify that causes novnc to hang.

- test-requirements.txt
- tests/test_websocket.py
- tests/test_websocketproxy.py
mox is pretty much unmaintained these days, however the OpenStack
project are actively maintaining mox3 (a Python 3 compatibile fork
with some other improvements).
websockify seems quite happy to use mox3 instead, so switch the
test dependency and associated imports to use mox3.
> Switch test dependency to mox3

- tests/test_websocketproxy.py
- websockify/websocketproxy.py
This commit adds support to unix sockets in the token plugin, thus it is
possible to have a token files like:
token: unix_socket:/path/to/socket_file
A single websockify instance will be able to handle multiple sockets.
Signed-off-by: Jose Ricardo Ziviani <jose@ziviani.net>
> Enable unix socket to work with token plugin

- tests/test_websocket.py
- websockify/websocket.py
The TCP_KEEPCNT option for sockets only work with the Linux kernel,
this isn't available for example in FreeBSD and Hurd, which makes the
package fail to build on these platforms. See Debian bug here:
https://bugs.debian.org/840035
> TCP_KEEPCNT doesn't exist in non-linux

- other/js/websockify.js
Fix for https://github.com/novnc/websockify/issues/280
Fixes error in websockify.js caused by upgrade to version 3 of the `ws` module, which contains breaking changes. See also: https://github.com/websockets/ws/pull/1104
> Fix websockify.js bug caused by upgrade to ws version 3

- tests/test_websockifyserver.py
test_websockifyserver: add FakeSocket.sendall method
The socket.sendall method is called indirectly via calls
to the python3.6 BaseHTTPRequestHandler.send_error method
which is called by both the Web*RequestHandler classes as
shown below:
```
======================================================================
ERROR: test_list_dir_with_file_only_returns_error (test_websockifyserver.WebSockifyRequestHandlerTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
File "tests/test_websockifyserver.py", line 115, in test_list_dir_with_file_only_returns_error
FakeSocket('GET / HTTP/1.1'), '127.0.0.1', server)
File "websockify/websockifyserver.py", line 94, in __init__
WebSocketRequestHandler.__init__(self, req, addr, server)
File …
```
> test_websockifyserver: add send_error stub (for python3.6)

- other/websockify.c
When compiling under cygwin, access() constants are not defined in fcntl.h:
```
websockify.c: In function ‘main’:
websockify.c:368:35: error: ‘R_OK’ undeclared (first use in this function)
if (access(settings.cert, R_OK) != 0) {
```
Including unistd.h allows compilation to complete.
> fix cygwin compilation

- other/js/package.json
- other/js/websockify.js
Fixes a problem that occurs in Chrome 61 where the following error message appears in the console:
'Failed to load module script: The server responded with a non-JavaScript MIME type of "".
Strict MIME type checking is enforced for module scripts per HTML spec.'
> Send Content-Type headers with static files

- other/websocket.c
- other/websockify.c
I found there is a missing option usage for 'run-once' in C websockify when compile and run with './websockify -h'. I added it into the USAGE string and maybe it's import to C websockify user.
> add run-once option help message and kill 9 warnings

- docs/websockify.1
- tests/test_websockifyserver.py
- websockify/auth_plugins.py
- websockify/websocketproxy.py
- websockify/websockifyserver.py
* Incorporates #190 without breaking compatibility towards old Python versions.
* A new plugin allows authenticating clients by the "common name" defined in their certificate.
* Added manual for certificate-based client authentication, including hints to which Python versions allow client certificate authentication.
* Adjusted test to work with new ssl.create_default_context.
* Incorporates changes as requested by CendioOssman.
> Added SSL-certificate-based client authentication.

- websockify/websockifyserver.py
If option '--key' is not specified. 'WebSockifyServer class' will
inital self.key as empty string. but ssl load_cert_chain function
will raise error 'no such file' with keyfile param empty string.
> fixed: ssl call error at function load_cert_chain.

- other/websocket.c
Instead of single certificate in one file it is sometimes customary to
chain multiple certificates into the same file. This is common practice
for CAs like letsencrypt that are providing intermediate certificates.
This patch switches loading of only one certificate to loading whole chain
of certificates.
The effects can be seen with e.g. the following command:
openssl s_client -showcerts -connect websockify-hostname:8080
Before the change the verify fails:
Certificate chain
0 s:/CN=websockify-hostname
i:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
After the change the verify passes:
Certificate chain
0 s:/CN=websockify-hostname
i:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
1 s:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
i:/O=Digital Signature Trust Co./CN=DST Root …
> C websockify: Load entire certificate chain

- other/Makefile
- other/websocket.c
b64_pton and b64_ntop functions are not portable and cannot be found in
all C library implementations (e.g. uClibc, musl).
Since c-websockify already has explicit dependency to openssl it can be
used to replace b64_pton/ntop with versions that are portable without
introducing too much additional code or dependencies.
Fixes #165
> C websockify: use openssl base64 encode/decode functions

- other/websocket.c
- other/websocket.h
- other/websockify.c
This pull request adds support for binary websocket protocol to make C websockify compatible with latest versions of noVNC.
The pull request consists of only commit https://github.com/novnc/websockify/pull/210/commits/53a49c2bbdc69575ea2f6db926790e12ed8de25a from an earlier pull request (#210). The commit was simply rebased and polished to apply cleanly onto the latest master
> C websockify: support for binary websocket protocol with HyBi/RFC 6455

- other/websocket.c
After fork() the parent process has a copy of clients file descriptor which
needs to be closed by the parent to prevent a descriptor leak.
Fixes #80
> C websockify: Fix file descriptor leak

- other/js/package.json
policyfile is not in use anymore so it should not be in the list of dependencies in package.json
> Remove policyfile from deps

- tests/test_websockifyserver.py
- websockify/websocketproxy.py
- websockify/websockifyserver.py
The change adds two options to WebSockifyServer. The first is a list of
SSL ciphers. The second is SSL options (intended use is to force a
specific TLS version).
Those two options allow for greater security of WebSocket Proxy.
> Enable setting SSL ciphers and SSL options

- run
- websockify/websocketproxy.py
- websockify/websockifyserver.py
Thanks to the work of @sakurai-youhei, Windows support is now back. It works well enough on Python 3.7. Older versions have not been tested.
Replaces #376 and fixes #67.
> Re-enable Windows support

- test-requirements.txt
- websockify/auth_plugins.py
- websockify/token_plugins.py
This patch is extending the token backend (plugins) with redis in ```websockify/token_plugins.py``` file and then adds a demo for that purpose ```runNoVncWs.sh``` it actually pulls the novnc and patches ```novnc/app/ui.js``` to pass through the token from ```vnc.html?token=token``` to the ```websockify``` WS url.
> novnc redis backed token demo

- websockify/websocketproxy.py
Fixed base class call to process_request() when usingThreadingMixIn
> websocketproxy small glitch on win32

- .travis.yml
Python 2.6 is not available in the newer environment, so make sure
we're getting the one we need for now.
> Use Ubuntu Trusty (14.04) for Travis

- run
- websockify/__main__.py
This file allows an easy invocation of websockify as a module, which is handy when running into shebang issues (like this: https://github.com/pypa/virtualenv/issues/596).
With this patch, `python -m websockify ...` has just the same behavior as `./run ...`.
> Add a __main__.py file for invocation as a module

- run
* Use double quotes around `"$@"` to fix invocation with arguments including spaces.
* Use double quotes around `"$(dirname "$0")"` to fix invocation inside a directory path including spaces.
* Use `set -e` to abort in case `cd` fails.
* Use `exec` to avoid forking an unnecessary wrapper process.
* Skip an unnecessary `cd` → `pwd` → `cd` dance, just use `cd`.
> run: Fix shell scripting bugs

- .travis.yml
- test-requirements.txt
Travis are dropping older Python environments, so update things to
something that reflects what current distributions are using (e.g. Red
Hat Enterprise Linux 7).
> Update test requirements

- websockify/token_plugins.py
For Python 3 compatibility.
The current syntax is leading to a syntax error when used with Python 3.
> Convert old print statement into function

- .gitignore
Taken from https://github.com/github/gitignore/blob/master/Python.gitignore
> Use GitHub's recommended .gitignore file for Python projects

- websockify/websocket.py
- websockify/websockifyserver.py
This matches the behaviour of SSLSocket, which we are trying to mimic. It also closely matches the behaviour of normal Socket which can be assumed to not have sent anything if an error occurs. We might actually
send some data, but the caller cannot really see that and must call us again as if no data was sent.
> Require same arguments on insufficient socket space

- .travis.yml
- test-requirements.txt
- tests/test_websocketproxy.py
- tests/test_websockifyserver.py
- tox.ini
- websockify/auth_plugins.py
- websockify/sysloghandler.py
- websockify/token_plugins.py
- websockify/websocket.py
- websockify/websocketproxy.py
- websockify/websocketserver.py
- websockify/websockifyserver.py
RHEL 6 is EOL now, so there should be nothing major left that doesn't have Python 3 support. So let's clean things up and remove all legacy handling.
> Remove Python 2 support

- README.md
There is a small typo in README.md.
Should read `accept` rather than `acccept`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: fix simple typo, acccept -> accept

- websockify/token_plugins.py
Currently, JWT tokens are reusable and can be intercepted. By using Expiration Time registered claim, it is possible to let expire them.
> Added exp claim for JWT token

- websockify/token_plugins.py
With the current parser logic, only tokens and servers that are separated by _exactly_ a colon and a space `: ` are detected as tokens. But when formatting one's token file with tabs, this breaks.
This commit changes the split characters to be a regular expression that matches all forms of whitespace, including spaces and tabs.
> Split token file by any whitespace after the colon, not just a space

- test-requirements.txt
Something is broken in pip so it installs a wrapt that doesn't support
Python 3.4. Work around this by manually request a version that is known
to work.
> Explicitly install old wrapt on Python 3.4

- websockify/websocketproxy.py
The global logging configuration should be applied to the root logger.
This way the configuration specified in the command line options will be propagated to all loggers.
This way all loggers will follow the configuration specified in the command line, and they will log to stderr, to a file or to syslog depending on the command line options given.
> Apply configuration to the root logger

- README.md
- docker/Dockerfile
- docker/docker-entrypoint.sh
Adding support to run with docker/podman or any other compatible container runtime.
To simplify the upgrades, the container is built on the official python image, in this case python:3.6 but it would be very easy to move to a different python version.
The container is built using the latest official release. To generate the Dockerfile for a new release is as simple as to bump the VERSION variable.
I also kept the same dependencies as currently used in the CI process: numpy<1.17 redis simplejson jwcrypto.
Finally, the users can provide files using the standard /data volume (certificates, novnc).
If you create a dockerhub account, let's say it is named `novnc` then you can build the image with:
```
docker build -t novnc/websockify:0.10.0 .
docker push novnc/websockify:0.10.0
```
And then …
> Docker support

- tests/test_token_plugins.py
- websockify/token_plugins.py
Newly realeased jwcryto versions 1.3 and 1.3.1 (both released this month) breaks the JWTTokenApi class and also the testing suite.
The reason is that the JWTTokenApi class uses a no longer supported way of creating a key:
```
key = jwt.JWK()
```
Actually instead of the **jwt** module it should use the **jwk** module for JWK():
```
key = jwk.JWK()
```
From 1.3 the jwt module no longer exposes JWK so the only option is to use the correct module.
> Tests break with jwcrypto>=1.3

- websockify/websocketproxy.py
some security scanning tools complain that exposing a directory for directory listing is a security violation. A option already exists to disable dir listing but it is not exposed to be used.
This PR simply exposes that option.
> expose --file-only option to disable dir listing

- tests/test_websocketserver.py
- websockify/websocket.py
- websockify/websocketserver.py
- websockify/websockifyserver.py
Let's try to hook the low level WebSocket object up to the `http.server` framework when possible, as it makes it easier to override things, and gives us some extra functionality.
> Connect WebSocket with Python's http.server classes

- websockify/websocketproxy.py
Insert rebinder at the head of the (possibly empty) LD_PRELOAD pathlist,
required for use cases relying on other preloaded libraries e.g. nss_wrapper.
> Preserve existing LD_PRELOAD, prepend rebinder 

- websockify/websocketproxy.py
- websockify/websockifyserver.py
https://github.com/novnc/websockify/issues/539
> Add option to listen to unix socket

- setup.py
- test-requirements.txt
- tests/test_token_plugins.py
- websockify/token_plugins.py
Various improvements to the TokenRedis plugin maintaining backwards compatibility:
- Support for password protected redis servers
- Support to select the redis database to use
- Support both for json and text format tokens (json seems a bit of an overhead in most cases)
- Verification of the token decoding and return None in case of a decoding error
- Eliminate the dependency with simplejson module since the json module in the standard lib is more than enough for our basic usage of using the loads
- Additional tests to verify all the functionality
> TokenRedis plugin improvements

- tests/test_token_plugins.py
- websockify/token_plugins.py
I suggest adding a new 'namespace' parameter to the TokenRedis plugin. This is useful when multiple clients use the same Redis instance.
Another parameter has been added to src and now the source format is as follows: 
`host[:port[:db[:password[:namespace]]]]`
All changes are covered by tests, and the old ones are updated.
> Add namespace value to TokenRedis source
