websockify/token_plugins.py
Changed the way the hostname and port are parsed in the token files to work with IPv6 addresses.
=> Add support for IPv6 addresses in tokens

websockify/websocket.py
Save log file descriptor so it's not closed when calling daemonize()
I apologize for not catching this earlier.
=> Fix log files when daemonizing

README.md
Fix minor typo in mini-webserver section
=> Add information about new logging files functionality in README

websockify/websocket.py
fixed trivial typos - heartbeat not possible otherwise
=> typo in ping() and pong()

include/wstelnet.js
Not much to say here… This makes it possible to use Tab-Completion via telnet
=> Allow tab to be sent via telnet

tests/echo.py, tests/echo_client.py, tests/load.py, websockify/auth_plugins.py, websockify/token_plugins.py, websockify/websocket.py, websockify/websocketproxy.py, websockify/websocketserver.py, websockify/websockifyserver.py
https://docs.python.org/2/howto/doanddont.html#except
=> Do not use base except: clauses

websockify/websocket.py, websockify/websocketproxy.py, websockify/websockifyserver.py
=> Do not confuse an empty message with a closed connection

other/js/websockify.js
=> Add recording feature to websockify.js.

README.md, tests/test_websocketproxy.py, websockify/auth_plugins.py, websockify/websocketproxy.py, websockify/websockifyserver.py
Added --web-auth option to require authentication to access the webserver.
BasicHTTPAuth plugin now issues 401 on bad credentials to allow the user to try again.
=> Auth changes

websockify/sysloghandler.py, websockify/websocketproxy.py
Just a minor improvement to --host-token
=> Port no longer included in token when using --host-token

websockify/websocket.py
* invalid struct unpacking
* undefined variable in error code path
* add missing argument
=> fix handling of "code"

tests/test_websockifyserver.py, websockify/websocketproxy.py, websockify/websockifyserver.py
=> Add option for cert key password

websockify/token_plugins.py
UnixDomainSocketDirectory token plugin can websockify all unix domain sockets under a specified directory. The token would be used as relative path to the specified path. It's very handy if QEMU is allocating VNC service on unix domain socket (with `vnc_auto_unix_socket` turned on).
Hope it helps.
=> Add UnixDomainSocketDirectory token plugin

websockify/token_plugins.py
The fix for issue #467 also added some more docs about the testing and format of redis responses.
To-do: add better logging
=> add docs and remove redundant ascii encoding

.github/workflows/test.yml, MANIFEST.in, setup.py, test-requirements.txt, websockify/websocketproxy.py
Various fixes to get the new actions running properly.
=> Github actions fixes

tests/test_token_plugins.py
Adding some basic tests for TokenRedis.
=> Add tests for TokenRedis

websockify/token_plugins.py
The classes in token_plugins.py should use of the logging facility instead of printing directly to sys.stderr.
This way the logging configuration created in websockify_init() will also apply to these classes.
This does not affect the default behavior defined in websockify_init() that is to log to stderr, but it will have an important effect in the case that --log-file or --syslog options are used.
=> Use logging instead of directly printing messages to sys.stderr

websockify/websocketproxy.py
When using the --verbose/-v option set root log level to DEBUG
=> When using the --verbose option set root log level to DEBUG

websockify/websocketproxy.py
This PR fixes #513.
Instead of looping until the queues are empty (as suggested by me in the issue) it drains the queues in the same loop pass.
Code could be refactored to reduce duplication but the potential for improvement here is not that big.
=> Drain queues before closing connections

docker/Dockerfile
Token plugin class JSONTokenAPI needs requests.
=> Add requests module

tests/test_token_plugins.py, websockify/token_plugins.py
main goal of this PR to ensure that all files are closed
=> migrate TokenPlugins from os.path to pathlib
